CandyUtils:
# The text shown when picking up a candy, note %type% gets replaced with the type of candy
  pickup_text: 'Вы взяли %type% конфету.'
  # Dictionary of candies and the respective text to show based on them
  candy_text:
    Rainbow: <color=#FF0000>Р</color><color=#FF7F00>а</color><color=#FFFF00>д</color><color=#00FF00>у</color><color=#0000FF>ж</color><color=#4B0082>н</color><color=#8A2BE2>у</color><color=#FF0000>ю
    Yellow: <color=#FFFF00>Жёлтую</color>
    Purple: <color=#800080>Фиолетовую</color>
    Red: <color=#FF0000>Красную</color>
    Green: <color=#008000>Зелёную</color>
    Blue: <color=#0000FF>Синию</color>
    Pink: <color=#FFC0CB>Розовую</color>
  # Text to be shown when hands are being severed
  severed_text: 'Трость мне в кость, твои руки теперь моя собственность'
better_coinflips:
# This is added to the effect message if the coin breaks.
  coin_breaks_message: |2-

    <color=white>Так-же твоя монетка была использована настолько часто, что сломалась.
  # The broadcast message when a coin is registered with no uses.
  coin_no_uses_message: 'Your coin had no uses to begin with!'
  hint_messages:
  - '<color=yellow>''Тебе выпала решка!'''
  - '<color=yellow>''Тебе выпал орёл!'''
  # Here you can set the message for each of these good coin effects.
  toss_on_cooldown_message: '<color=White>''Пока-что ты не можешь сделать этого'''
  red_card_message: '<color=green>''Ты получил карту Facility Manager!'''
  containment_engineer_card_message: '<color=green>''Ты получил карту Containment Engineer!'''
  medi_kit_message: '<color=green>''Ты получил аптечный набор!'''
  tp_to_escape_message: '<color=green>''Теперь ты можешь бежать! Ты ведь этого хотел, верно?'''
  magic_heal_message: '<color=green>''Ты магическим образом был исцелён!'''
  health_increase_message: '<color=green>''Ты получил на 10% больше HP!'''
  neat_hat_message: '<color=green>''Ты получил красивую шляпу!'''
  random_good_effect_message: '<color=green>''Ты получил случайный эффект'''
  one_ammo_logicer_message: '<color=green>''У тебя теперь ствол...'''
  lightbulb_message: '<color=green>''У тебя теперь ламповая блестяшка!'''
  pink_candy_message: '<color=green>''Ух, какая конфетка!'''
  bad_revo_message: '<color=green>''Что это за мерзость!?'''
  empty_hid_message: '<color=green>''ТЫ ЧТО, ПОЛУЧИЛ МИКРОХИД?'''
  force_respawn_message: '<color=green>''Кто-то появился... наверное.'''
  size_change_message: '<color=green>''Тебя загномили.'''
  random_item_message: '<color=green>''Ты получил случайный предмет!'''
  # Here you can set the message for each of these bad coin effects.
  hp_reduction_message: '<color=red>''Твоё здоровье уменьшилось на 30%.'''
  tp_to_class_d_cells_message: '<color=red>''Тебя телепортировало к Class D.'''
  tp_to_class_d_cells_after_warhead_message: '<color=red>''Тебя перенесло в радиоактивную зону'''
  random_bad_effect_message: '<color=red>''Вы получили случайный эффект'''
  warhead_stop_message: '<color=red>''Боеголовка была остановлена'''
  warhead_start_message: '<color=red>''Боеголовка была запущена.'''
  lights_out_message: '<color=red>''Вырубаем свет'''
  live_grenade_message: '<color=red>''Берегись!'''
  troll_flash_message: '<color=red>''Что это упало?'''
  tp_to_random_scp_message: '<color=red>''Ты был телепортирован к SCP!'''
  small_damage_message: '<color=red>''Ты потерял 15HP.'''
  huge_damage_message: '<color=red>''Ты потерял много здоровья'''
  primed_vase_message: '<color=red>''Бабуля наносит тебе визит!'''
  shit_pants_message: '<color=red>''Ержан, ты обосрался!'''
  fake_scp_kill_message: '<color=red>''Ты что, убил SCP?!'''
  turn_into_scp_message: '<color=red>''Теперь ты SCP!'''
  inventory_reset_message: '<color=red>''Ты потерял все вещи!'''
  class_swap_message: '<color=red>''Вот, что я называю Uno Reverse Card!'''
  instant_explosion_message: '<color=red>''РАЗРЫВНАЯ!!'''
  player_swap_message: '<color=red>''Ты поменялся местами со случайным игроком!.'''
  player_swap_if_one_alive_message: '<color=red>''Ты должен был поменяться с кем-то местами, но никого нет в живых!'''
  kick_message: '<color=red>''Пока!'''
  spect_swap_player_message: '<color=red>''Ты сделал чей-то раунд лучше!'''
  spect_swap_spect_message: '<color=red>''Да ты везунчик!'''
  spect_swap_no_spects_message: '<color=red>''Тебе повезло, ведь здесь нет живых наблюдателей, чтобы тебя заменить...'''
  tesla_tp_message: '<color=red>''Так ты фанат электричества?'''
  tesla_tp_after_warhead_message: '<color=red>''Тебя перенесло в радиоактивную зону.'''
  # This message will be broadcast to both players.
  inventory_swap_message: '<color=red>''Твой инвентарь был заменён со случайным игроком!'''
  inventory_swap_one_player_message: '<color=red>''Ты не можешь ни с кем поменяться местами, поэтому ты теряешь здоровье.'''
  random_teleport_message: '<color=red>''Ты был случайно телепортирован.'''
  random_teleport_warhead_detonated_message: '<color=red>''Боеголовка взорвана, но у тебя есть конфета.'''
  handcuff_message: '<color=red>''Вы были арестованы за, нуу, эмм... разжигание войны... или что-то такое...'''
map_editor_reborn:
  mode_creating: '<color=yellow>Mode:</color> <color=green>Creating</color>'
  mode_deleting: '<color=yellow>Mode:</color> <color=red>Deleting</color>'
  mode_selecting: '<color=yellow>Mode:</color> <color=yellow>Selecting</color>'
  mode_copying: '<color=yellow>Mode:</color> <color=#34B4EB>Copying to the ToolGun</color>'
