AT:
# Enable/Disable AdminTools.
  is_enabled: true
  debug: false
  # Should the tutorial class be in God Mode? Default: true
  god_tuts: false
better_coinflips:
# Whether or not the plugin should be enabled. Default: true
  is_enabled: true
  # Whether or not debug logs should be shown. Default: false
  debug: false
  # The amount of base game spawned coins that should be removed. Default: 4
  default_coins_amount: 4
  # The ItemType of the item to be replaced with a coin and the amount to be replaced, the item is supposed to be something found in SCP pedestals.
  item_to_replace:
    SCP500: 2
  # The boundaries of the random range of throws each coin will have before it breaks. The upper bound is exclusive.
  min_max_default_coins:
  - 1
  - 4
  # Time in seconds between coin toses.
  coin_cooldown: 5
  # The duration of the broadcast informing you about your 'reward'. Default: 3
  broadcast_time: 3
  # The duration of the hint telling you if you got heads or tails. Set to 0 or less to disable.
  hint_duration: 3
  # The duration of the map blackout. Default: 10
  map_blackout_time: 10
  # The fuse time of the grenade falling on your head. Default: 3.25
  live_grenade_fuse_time: 3.25
  # List of bad effects that can be applied to the players. List available at: https://exiled-team.github.io/EXILED/api/Exiled.API.Enums.EffectType.html
  bad_effects:
  - Asphyxiated
  - Bleeding
  - Blinded
  - Burned
  - Concussed
  - Corroding
  - CardiacArrest
  - Deafened
  - Decontaminating
  - Disabled
  - Ensnared
  - Exhausted
  - Flashed
  - Hemorrhage
  - Hypothermia
  - InsufficientLighting
  - Poisoned
  - PocketCorroding
  - SeveredHands
  - SinkHole
  - Stained
  - Traumatized
  # List of good effects that can be applied to the players. List available at: https://exiled-team.github.io/EXILED/api/Exiled.API.Enums.EffectType.html
  good_effects:
  - BodyshotReduction
  - DamageReduction
  - Invigorated
  - Invisible
  - MovementBoost
  - RainbowTaste
  - Scp1853
  - Scp207
  - Vitality
  # The % chance of receiving a Facility Manager keycard instead of a Containment Engineer one.
  red_card_chance: 15
  # The kick reason.
  kick_reason: 'The coin kicked your ass.'
  # The list of SCP's that you can turn into by using the coin.
  valid_scps:
  - Scp049
  - Scp096
  - Scp106
  - Scp173
  - Scp0492
  - Scp939
  # List of ignored roles for the PlayerSwap effect (#17)
  player_swap_ignored_roles:
  - Spectator
  - Filmmaker
  - Overwatch
  - Scp079
  - Tutorial
  # List of ignored roles for the InventorySwap effect (#17)
  inventory_swap_ignored_roles:
  - Spectator
  - Filmmaker
  - Overwatch
  - Scp079
  - Tutorial
  - Scp049
  - Scp096
  - Scp106
  - Scp173
  - Scp0492
  - Scp939
  - Scp3114
  items_to_give:
  - Adrenaline
  - Coin
  - Flashlight
  - Jailbird
  - Medkit
  - Painkillers
  - Radio
  - ArmorCombat
  - ArmorHeavy
  - ArmorLight
  - GrenadeFlash
  - GrenadeHE
  - GunA7
  - GunCom45
  - GunCrossvec
  - GunLogicer
  - GunRevolver
  - GunShotgun
  - GunAK
  - GunCOM15
  - GunCOM18
  - GunE11SR
  - GunFSP9
  - GunFRMG0
  rooms_to_teleport:
  - EzCafeteria
  - EzCheckpointHallway
  - EzCollapsedTunnel
  - EzConference
  - EzCrossing
  - EzCurve
  - EzDownstairsPcs
  - EzGateA
  - EzGateB
  - EzIntercom
  - EzPcs
  - EzStraight
  - EzTCross
  - EzUpstairsPcs
  - EzVent
  - Hcz049
  - Hcz079
  - Hcz096
  - Hcz106
  - Hcz939
  - HczArmory
  - HczCrossing
  - HczCurve
  - HczElevatorA
  - HczElevatorB
  - HczEzCheckpointA
  - HczEzCheckpointB
  - HczHid
  - HczNuke
  - HczServers
  - HczStraight
  - HczTCross
  - HczTesla
  - HczTestRoom
  - Lcz173
  - Lcz330
  - Lcz914
  - LczAirlock
  - LczArmory
  - LczCafe
  - LczCheckpointA
  - LczCheckpointB
  - LczClassDSpawn
  - LczCrossing
  - LczCurve
  - LczGlassBox
  - LczPlants
  - LczStraight
  - LczTCross
  - LczToilets
  - Surface
  # The chance of these good effects happening. It's a proportional chance not a % chance.
  keycard_chance: 20
  medical_kit_chance: 35
  tp_to_escape_chance: 5
  heal_chance: 10
  more_hp_chance: 10
  hat_chance: 10
  random_good_effect_chance: 30
  one_ammo_logicer_chance: 1
  lightbulb_chance: 15
  pink_candy_chance: 10
  bad_revo_chance: 5
  empty_hid_chance: 5
  force_respawn_chance: 15
  size_change_chance: 20
  random_item_chance: 35
  # The chance of these bad effects happening. It's a proportional chance not a % chance.
  hp_reduction_chance: 20
  tp_to_class_d_cells_chance: 5
  random_bad_effect_chance: 20
  warhead_chance: 10
  lights_out_chance: 20
  live_he_chance: 30
  troll_flash_chance: 50
  scp_tp_chance: 20
  one_hp_left_chance: 15
  primed_vase_chance: 20
  shit_pants_chance: 40
  fake_cassie_chance: 50
  turn_into_scp_chance: 30
  inventory_reset_chance: 20
  class_swap_chance: 10
  instant_explosion_chance: 10
  player_swap_chance: 20
  kick_chance: 5
  spect_swap_chance: 10
  tesla_tp_chance: 15
  inventory_swap_chance: 20
  handcuff_chance: 10
  random_teleport_chance: 15
exiled_credits:
  is_enabled: true
  debug: false
  # Info side - Badge, CustomPlayerInfo, FirstAvailable
  mode: FirstAvailable
  # Overrides badge if exists
  badge_override: false
  # Overrides Custom Player Info if exists
  custom_player_info_override: false
  # Whether or not the plugin should ignore a player's DNT flag. By default (false), players with DNT flag will not be checked for credit tags.
  ignore_dnt_flag: false
exiled_custom_items:
# Indicates whether this plugin is enabled or not.
  is_enabled: true
  debug: false
  # The hint that is shown when someone pickups a custom item.
  picked_up_hint:
  # The broadcast content
    content: |-
      You have picked up a {0}
      {1}
    # The broadcast duration
    duration: 10
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # The hint that is shown when someone selects a custom item.
  selected_hint:
  # The broadcast content
    content: |-
      You have selected a {0}
      {1}
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
exiled_custom_roles:
# Whether or not the plugin is enabled.
  is_enabled: true
  # Whether or not debug messages should be shown.
  debug: false
  # The hint that is shown when someone gets a custom role.
  got_role_hint:
  # The broadcast content
    content: |-
      You have spawned as a {0}
      {1}
    # The broadcast duration
    duration: 6
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # The hint that is shown when someone used a custom ability.
  used_ability_hint:
  # The broadcast content
    content: |-
      Ability {0} has been activated.
      {1}
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # Whether or not Keypress ability activations will work on the server.
  use_keypress_activation: true
  # Whether or not abilities that are not selected as the current keypress ability can still be activated.
  activate_only_selected: true
  # The hint showed to players when they fail to preform an action.
  failed_action_hint:
  # The broadcast content
    content: 'Failed to preform action: {0}'
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # The hint that is shown to players when they switch abilities.
  switched_ability_hint:
  # The broadcast content
    content: 'Selected ability {0}'
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
exiled_events:
  is_enabled: true
  debug: false
  # Indicates whether events are patched only if they have delegates subscribed to them
  use_dynamic_patching: true
  # Indicates whether SCP-173 can be blocked or not by the tutorial
  can_tutorial_block_scp173: true
  # Indicates whether SCP-096 can be triggered or not by the tutorial
  can_tutorial_trigger_scp096: true
  # Indicates whether SCP-049 can sense tutorial players or not
  can_scp049_sense_tutorial: true
  # Indicates whether tutorial is affected by SCP-079 scan.
  tutorial_not_affected_by_scp079_scan: false
  # Indicates whether flashbangs flash original thrower.
  can_flashbangs_affect_thrower: false
  # Indicates whether the name tracking (invisible EXILED version string added to the end of the server name) is enabled or not
  is_name_tracking_enabled: true
  # Indicates whether the inventory should be dropped before being set as spectator, through commands or plugins
  should_drop_inventory: true
  # Indicates whether the blood can be spawned or not
  can_spawn_blood: true
  # Indicates whether thrown keycards can affect doors that don't require any permissions
  can_keycard_throw_affect_doors: false
  # Indicates whether configs have to be reloaded every round restart
  should_reload_configs_at_round_restart: false
  # Indicates whether translations has to be reloaded every round restart
  should_reload_translations_at_round_restart: false
  # Indicates whether bans should be logged or not
  should_log_bans: true
  # Whether or not to log RA commands.
  log_ra_commands: true
exiled_permissions:
# Indicates whether the debug should be shown or not
  should_debug_be_shown: false
  # The permissions folder path
  folder: '/home/pavelik123/.config/EXILED/Configs'
  # The permissions full path
  full_path: '/home/pavelik123/.config/EXILED/Configs/permissions.yml'
  is_enabled: true
  debug: false
scp1162:
# Is the plugin enabled?
  is_enabled: true
  # Should debug messages be displayed?
  debug: false
  # Use Hints instead of Broadcast?
  use_hints: true
  # Change the message that displays when you drop an item through SCP-1162.
  item_drop_message: '<i>You try to drop the item through <color=yellow>SCP-1162</color> to get another...</i>'
  item_drop_message_duration: 5
  # The list of item chances.
  chances:
  - KeycardO5
  - SCP500
  - MicroHID
  - KeycardMTFCaptain
  - KeycardContainmentEngineer
  - SCP268
  - GunCOM15
  - SCP207
  - Adrenaline
  - GunCOM18
  - KeycardFacilityManager
  - Medkit
  - KeycardMTFOperative
  - KeycardGuard
  - GrenadeHE
  - KeycardZoneManager
  - KeycardGuard
  - Radio
  - Ammo9x19
  - Ammo12gauge
  - Ammo44cal
  - Ammo556x45
  - Ammo762x39
  - GrenadeFlash
  - KeycardScientist
  - KeycardJanitor
  - Coin
  - Flashlight
