AT:
# Enable/Disable AdminTools.
  is_enabled: true
  debug: false
  # Should the tutorial class be in God Mode? Default: true
  god_tuts: false
exiled_credits:
  is_enabled: true
  debug: false
  # Info side - Badge, CustomPlayerInfo, FirstAvailable
  mode: FirstAvailable
  # Overrides badge if exists
  badge_override: false
  # Overrides Custom Player Info if exists
  custom_player_info_override: false
  # Whether or not the plugin should ignore a player's DNT flag. By default (false), players with DNT flag will not be checked for credit tags.
  ignore_dnt_flag: false
exiled_custom_items:
# Indicates whether this plugin is enabled or not.
  is_enabled: true
  debug: false
  # The hint that is shown when someone pickups a custom item.
  picked_up_hint:
  # The broadcast content
    content: |-
      You have picked up a {0}
      {1}
    # The broadcast duration
    duration: 10
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # The hint that is shown when someone selects a custom item.
  selected_hint:
  # The broadcast content
    content: |-
      You have selected a {0}
      {1}
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
exiled_custom_roles:
# Whether or not the plugin is enabled.
  is_enabled: true
  # Whether or not debug messages should be shown.
  debug: false
  # The hint that is shown when someone gets a custom role.
  got_role_hint:
  # The broadcast content
    content: |-
      You have spawned as a {0}
      {1}
    # The broadcast duration
    duration: 6
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # The hint that is shown when someone used a custom ability.
  used_ability_hint:
  # The broadcast content
    content: |-
      Ability {0} has been activated.
      {1}
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # Whether or not Keypress ability activations will work on the server.
  use_keypress_activation: true
  # Whether or not abilities that are not selected as the current keypress ability can still be activated.
  activate_only_selected: true
  # The hint showed to players when they fail to preform an action.
  failed_action_hint:
  # The broadcast content
    content: 'Failed to preform action: {0}'
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # The hint that is shown to players when they switch abilities.
  switched_ability_hint:
  # The broadcast content
    content: 'Selected ability {0}'
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
exiled_events:
  is_enabled: true
  debug: false
  # Indicates whether events are patched only if they have delegates subscribed to them
  use_dynamic_patching: true
  # Indicates whether SCP-173 can be blocked or not by the tutorial
  can_tutorial_block_scp173: true
  # Indicates whether SCP-096 can be triggered or not by the tutorial
  can_tutorial_trigger_scp096: true
  # Indicates whether SCP-049 can sense tutorial players or not
  can_scp049_sense_tutorial: true
  # Indicates whether tutorial is affected by SCP-079 scan.
  tutorial_not_affected_by_scp079_scan: false
  # Indicates whether flashbangs flash original thrower.
  can_flashbangs_affect_thrower: false
  # Indicates whether the name tracking (invisible EXILED version string added to the end of the server name) is enabled or not
  is_name_tracking_enabled: true
  # Indicates whether the inventory should be dropped before being set as spectator, through commands or plugins
  should_drop_inventory: true
  # Indicates whether the blood can be spawned or not
  can_spawn_blood: true
  # Indicates whether thrown keycards can affect doors that don't require any permissions
  can_keycard_throw_affect_doors: false
  # Indicates whether configs have to be reloaded every round restart
  should_reload_configs_at_round_restart: false
  # Indicates whether translations has to be reloaded every round restart
  should_reload_translations_at_round_restart: false
  # Indicates whether bans should be logged or not
  should_log_bans: true
  # Whether or not to log RA commands.
  log_ra_commands: true
exiled_permissions:
# Indicates whether the debug should be shown or not
  should_debug_be_shown: false
  # The permissions folder path
  folder: 'C:\Users\Pavel\AppData\Roaming\EXILED\Configs'
  # The permissions full path
  full_path: 'C:\Users\Pavel\AppData\Roaming\EXILED\Configs\permissions.yml'
  is_enabled: true
  debug: false
scp1162:
# Is the plugin enabled?
  is_enabled: true
  # Should debug messages be displayed?
  debug: false
  # Use Hints instead of Broadcast?
  use_hints: true
  # Change the message that displays when you drop an item through SCP-1162.
  item_drop_message: '<i>You try to drop the item through <color=yellow>SCP-1162</color> to get another...</i>'
  item_drop_message_duration: 5
  # The list of item chances.
  chances:
  - KeycardO5
  - SCP500
  - KeycardMTFCaptain
  - KeycardContainmentEngineer
  - SCP268
  - GunCOM15
  - SCP207
  - Adrenaline
  - GunCOM18
  - KeycardFacilityManager
  - Medkit
  - KeycardMTFOperative
  - KeycardGuard
  - GrenadeHE
  - KeycardZoneManager
  - KeycardGuard
  - Radio
  - Ammo9x19
  - Ammo12gauge
  - Ammo44cal
  - Ammo556x45
  - Ammo762x39
  - GrenadeFlash
  - KeycardScientist
  - KeycardJanitor
  - Coin
  - Flashlight
