user:
  default: true
  inheritance: [ ]
  permissions:
    - testplugin.user
owner:
  default: false
  inheritance: [ ]
  permissions:
    - .*
    - at.kill
admin:
  default: false
  inheritance:
    - moderator
  permissions:
    - .*
moderator:
  default: false
  inheritance: [ ]
  permissions:
    - at.hp
    - PlayerPermissions.PlayersManagement
    - at.tut
stajer:
  default: false
  inheritance: [ ]
  permissions:
    - at.hp
    - at.tut
