# Whether the default player spawnpoints should be removed. Keep in mind, that given role spawnpoint will be removed only if there is at least one custom spawn point of that type.
remove_default_spawn_points: false
# List of possible names for ragdolls spawned by RagdollSpawnPoints.
ragdoll_role_names:
  ClassD:
  - 'D-001'
vanilla_doors: {}
vanilla_tesla_properties:
  ignored_roles: []
  ignored_items: []
  inventory_item: true
  damage_multiplier: 1
doors: 
- door_type: LightContainmentDoor
  is_open: false
  is_locked: true
  keycard_permissions: None
  ignored_damage_sources: Weapon
  door_health: 9999
  lock_on_event: None
  position:
    x: 14.86443
    y: 11.74155
    z: 12.25622
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
- door_type: LightContainmentDoor
  is_open: false
  is_locked: true
  keycard_permissions: None
  ignored_damage_sources: Weapon
  door_health: 9999
  lock_on_event: None
  position:
    x: 16.79447
    y: 11.75038
    z: 12.25621
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
- door_type: LightContainmentDoor
  is_open: false
  is_locked: true
  keycard_permissions: None
  ignored_damage_sources: Weapon
  door_health: 9999
  lock_on_event: None
  position:
    x: 18.81608
    y: 11.72787
    z: 12.25621
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
- door_type: LightContainmentDoor
  is_open: false
  is_locked: true
  keycard_permissions: None
  ignored_damage_sources: Weapon
  door_health: 9999
  lock_on_event: None
  position:
    x: 20.81961
    y: 11.73399
    z: 12.25621
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
work_stations: []
item_spawn_points:
- item: 'SCP207'
  attachments_code: '-1'
  spawn_chance: 100
  number_of_items: 1
  number_of_uses: 1
  use_gravity: true
  can_be_picked_up: true
  position:
    x: 21.52519
    y: 13.11686
    z: 5.73842
  rotation:
    x: 270
    y: -90
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
player_spawn_points: []
ragdoll_spawn_points: []
shooting_targets: []
primitives: []
light_sources: []
room_lights: []
teleports:
- target_teleporters:
  - id: 36
    chance: 100
  allowed_roles: []
  cooldown: 10
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 
  player_rotation_y: 
  room_type: Lcz173
  object_id: 37
  position:
    x: -4.800005
    y: 3.5
    z: -4.768372E-07
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 0.7
    y: 0.7
    z: 0.7
- target_teleporters:
  - id: 37
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  cooldown: 0
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 
  player_rotation_y: 
  room_type: Lcz173
  object_id: 38
  position:
    x: 4
    y: 16
    z: -0.1999965
  rotation:
    x: 180
    y: 180
    z: 180
  scale:
    x: 3
    y: 1
    z: 3
- target_teleporters:
  - id: 38
    chance: 100
  allowed_roles: []
  cooldown: 10
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 
  player_rotation_y: 
  room_type: Lcz173
  object_id: 39
  position:
    x: 4.300005
    y: 12.9
    z: -0.3000026
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 39
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  cooldown: 0
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 
  player_rotation_y: 
  room_type: Lcz173
  object_id: 40
  position:
    x: -5
    y: 5.8
    z: -4.768372E-07
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 0.7
    y: 0.7
    z: 0.7
lockers: []
schematics:
- schematic_name: 'scp236room'
  culling_type: None
  is_pickable: false
  position:
    x: 2.699997
    y: 11
    z: 0.5449984
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
- schematic_name: 'rlight'
  culling_type: None
  is_pickable: false
  position:
    x: 10.2
    y: 11.4
    z: 4.6
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
- schematic_name: 'rlight'
  culling_type: None
  is_pickable: false
  position:
    x: 10.51082
    y: 11.71677
    z: 10.43989
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
- schematic_name: 'rlight'
  culling_type: None
  is_pickable: false
  position:
    x: 10.52257
    y: 14.19223
    z: 10.41237
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
- schematic_name: 'purlight'
  culling_type: None
  is_pickable: false
  position:
    x: 21.51083
    y: 13.41944
    z: 5.748667
  rotation:
    x: 0
    y: -90
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz173
